-- Documentation migration for auth_leaked_password_protection setting.
-- KIM-391: Fix remaining Supabase security linter warnings.
--
-- The Supabase security linter warns that "auth_leaked_password_protection" is disabled
-- in the current environment. This setting cannot be controlled via SQL migrations—
-- it is a Supabase project-level configuration.
--
-- To enable this setting:
-- 1. Log in to the Supabase dashboard
-- 2. Navigate to Authentication > Providers > Email
-- 3. Check "Enable password-based authentication"
-- 4. Enable "Protect against leaked passwords"
-- 5. Save the configuration
--
-- Once enabled, Supabase Auth will:
-- - Check user passwords against the HaveIBeenPwned database
-- - Block sign-ups with compromised passwords
-- - Block password updates that use compromised passwords
--
-- This is a security best practice and should be enabled in all environments.
